@echo off
for %%f in (MP3, Ogg, FLAC, Wav, AIFF, WMA, Movie, Shorten, Musepack, APE, WavPack, OggFLAC, DFF, DSF) do (
	(echo # This file is automatically generated.
	echo # Edit template.pl and run makeformats.bat to update all formats.
	echo package Plugins::MultiDisc::Formats::%%f;
	echo use base 'Slim::Formats::%%f';
	type template.pl) >%%f.pm
)
